dist: trusty

matrix:
  fast_finish: true

language: python

python:
  - 3.6
  - 2.7

install:
  - pip install -q flake8 coverage codecov

script:
  - "python -m coverage run -m unittest discover tests \"*_test.py\""
  - "python -m coverage xml"
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then && python -m flake8 wind; fi

after_success:
  - "codecov"
